name: CD-traefik

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          all_envs: true
          script: cd && cd git-workflows && bash ./script.sh ${{ github.event.repository.name }} ${{ vars.PROJECT_NAME }} | printenv
